In [158]:
import torch
import torch.nn as nn

experts = nn.ModuleList([nn.Linear(128, 10) for _ in range(5)])
experts

ModuleList(
  (0-4): 5 x Linear(in_features=128, out_features=10, bias=True)
)

In [159]:
router_output = torch.Tensor([[0.5696, 0.4304, 0.0000],
                               [0.0000, 0.2981, 0.7019]])

router_output

tensor([[0.5696, 0.4304, 0.0000],
        [0.0000, 0.2981, 0.7019]])

In [160]:
topk_indices = torch.Tensor([[0, 1],
                             [2, 1]])
topk_indices

tensor([[0., 1.],
        [2., 1.]])

In [161]:
x = torch.rand((2, 128))

In [162]:
embedding_mask = (topk_indices == 2)
embedding_mask

tensor([[False, False],
        [ True, False]])

In [163]:
embedding_mask.any(dim=1)

tensor([False,  True])

In [164]:
selected_embedding = x[embedding_mask.any(dim=1)]
selected_embedding.shape

torch.Size([1, 128])

In [165]:
expert_output = experts[0](selected_embedding)
expert_output.shape

torch.Size([1, 10])

In [166]:
weighted_gate = router_output[:, 2][embedding_mask.any(dim=1)]
weighted_gate

tensor([0.7019])

In [167]:
final_output = torch.zeros((2, 10))
final_output.shape

torch.Size([2, 10])

In [168]:
final_output[embedding_mask.any(dim=1)]

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [169]:
final_output[embedding_mask.any(dim=1)] =  expert_output * weighted_gate.unsqueeze(1)

In [170]:
final_output

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [-0.0911,  0.4237,  0.1218,  0.2765,  0.1078,  0.1962,  0.0067,  0.0514,
         -0.3243, -0.2725]], grad_fn=<IndexPutBackward0>)

In [6]:
import torch

indices = torch.tensor([[2, 3, 0],
                        [2, 3, 0],
                        [2, 3, 0]])

gates = torch.tensor([[0.4011, 0.3944, 0.2045],
                      [0.4431, 0.3265, 0.2303],
                      [0.4362, 0.3567, 0.2072]])

In [12]:
(indices == 0)

tensor([[False, False,  True],
        [False, False,  True],
        [False, False,  True]])

In [13]:
(gates * (indices == 0))

tensor([[0.0000, 0.0000, 0.2045],
        [0.0000, 0.0000, 0.2303],
        [0.0000, 0.0000, 0.2072]])

In [2]:
top_k_indices =[
  [0, 2],
  [1, 2],
  [0, 1]
]

In [6]:
import torch
import torch.nn.functional as F

import torch.nn.functional as F

top_k_indices_tensor = torch.tensor(top_k_indices, dtype=torch.long)
expert_mask = F.one_hot(top_k_indices_tensor, num_classes=3)
expert_mask

tensor([[[1, 0, 0],
         [0, 0, 1]],

        [[0, 1, 0],
         [0, 0, 1]],

        [[1, 0, 0],
         [0, 1, 0]]])

In [8]:
a = expert_mask.sum(dim=1)
a

tensor([[1, 0, 1],
        [0, 1, 1],
        [1, 1, 0]])

In [13]:
a.float().mean(dim=0)

tensor([0.6667, 0.6667, 0.6667])